s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: models-resources
s3_key_prefix: thermoscope
s3_endpoint: us-east-1
gzip: true

cloudfront_distribution_id: E25WBBUN8ZQYRA
cloudfront_invalidate_root: true
cloudfront_wildcard_invalidation: true

<% if ENV['TRAVIS_BRANCH'] == 'production' %>
# in this case we are going to deploy this branch to the top level of the domain
# so we need to ignore the version and branch folders
ignore_on_server: ^thermoscope/(version/|branch/)
<% else %>
# in this case we are going to deploy this code to a subfolder of either the branch
# or version folder. So ignore everything except this folder.
ignore_on_server: ^(?!thermoscope/<%= Regexp.escape(ENV['DEPLOY_DIR']) %>/)
<% end %>
max_age:
  "thermoscope/*": 600 # 10 minutes
  "thermoscope/version/*": 31536000 # 1 year
  "thermoscope/branch/*": 0

cloudfront_distribution_config:
  aliases:
    quantity: 1
    items:
      - thermoscope.concord.org
